tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field: common.title
      -
        display: 'Meta Tags'
        instructions: 'Default meta tags to be applied'
        fields:
          -
            import: meta_tags
